# Config file for automatic testing at travis-ci.org
language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

before_install:
  - pip install codecov

# command to run tests using coverage, e.g. python setup.py test
script: python setup.py test

services:
  - postgresql

after_success:
  - codecov
