# Config file for automatic testing at travis-ci.org
sudo: false
language: python
python:
  - "3.8"
install: pip install -q tox-travis
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=3.2
matrix:
  fast_finish: true
  include:
    - python: "3.8"
      env: TOXENV="lint"
script: tox
after_success:
  - pip install -q codecov scrutinizer-ocular
  - codecov -e TOXENV,DJANGO
  - ocular --data-file ".coverage" --config-file ".coveragerc"
notifications:
  email: false
